-- PNWCardVault catalog: unowned shared inventory + orders without PII.
create table if not exists drops (
  id          serial primary key,
  slug        text unique not null,
  title       text not null,
  subtitle    text,
  kind        text not null,
  status      text not null default 'open',
  image_key   text not null,
  blurb       text,
  created_at  timestamptz not null default now()
);

create table if not exists products (
  id                serial primary key,
  slug              text unique not null,
  title             text not null,
  player            text,
  set_name          text,
  year              integer,
  sport             text not null,
  kind              text not null,
  parallel          text,
  serial_num        text,
  grade             text,
  price_cents       integer not null,
  compare_at_cents  integer,
  qty               integer not null default 1 check (qty >= 0),
  description       text,
  image_key         text not null default 'face',
  featured          boolean not null default false,
  drop_id           integer references drops(id),
  created_at        timestamptz not null default now()
);

create index if not exists products_sport_idx on products (sport);
create index if not exists products_kind_idx on products (kind);
create index if not exists products_drop_id_idx on products (drop_id);
create index if not exists products_featured_idx on products (featured);

create table if not exists orders (
  id           serial primary key,
  code         text unique not null,
  items_json   text not null,
  total_cents  integer not null,
  status       text not null default 'placed',
  created_at   timestamptz not null default now()
);

insert into drops (id, slug, title, subtitle, kind, status, image_key, blurb) values
  (1, 'friday-nba-vault', 'Friday NBA Vault', 'Singles + hobby spots', 'show', 'open', 'fan',
   'A tight NBA singles list plus a handful of 2026 Prizm hobby spots. Share the drop link — whoever clicks it can grab a card before the show.'),
  (2, 'wnba-prizm-spots', 'WNBA Prizm Night', 'Singles, autos, FOTL spots', 'show', 'open', 'wnba-holo',
   'WNBA singles and First Off The Line spots. Send the link in the chat; the listing is the checkout.'),
  (3, 'rain-city-nonsport', 'Rain City Non-Sport', 'Chrome antiheroes + stickers', 'show', 'open', 'comic',
   'Non-sport night. Comic chrome and sticker cards, listed as shareable buy links.');

select setval('drops_id_seq', 3);

insert into products (
  slug, title, player, set_name, year, sport, kind, parallel, serial_num, grade,
  price_cents, compare_at_cents, qty, description, image_key, featured, drop_id
) values
  (
    'cooper-flagg-chrome-rc',
    '2026 Topps Chrome Cooper Flagg Rated Rookie',
    'Cooper Flagg',
    'Topps Chrome',
    2026,
    'basketball',
    'single',
    'Silver',
    null,
    'Raw',
    8900,
    11000,
    1,
    'Raw 2026 Topps Chrome rated rookie. Silver refractive. Corners look sharp under the loupe; centering a hair west. One available — the buy link is the listing.',
    'bball-rookie',
    true,
    1
  ),
  (
    'caitlin-clark-prizm-silver',
    'Caitlin Clark Prizm Silver RC',
    'Caitlin Clark',
    'Panini Prizm',
    2025,
    'wnba',
    'single',
    'Silver',
    null,
    'Raw',
    7200,
    8500,
    1,
    'Prizm silver rookie. Surface is clean, no print lines that catch the light. Packed and listed from the vault — share the link to sell it.',
    'wnba-holo',
    true,
    2
  ),
  (
    'sga-prizm-silver-psa10',
    'Shai Gilgeous-Alexander Prizm Silver PSA 10',
    'Shai Gilgeous-Alexander',
    'Panini Prizm',
    2024,
    'basketball',
    'slab',
    'Silver',
    null,
    'PSA 10',
    14500,
    null,
    1,
    'Gem mint silver Prizm in a fresh slab. Case is clean, label is straight. Ships in a padded vault mailer.',
    'slab',
    true,
    null
  ),
  (
    'paige-bueckers-green-laser',
    '2026 Donruss Paige Bueckers Green Laser /399',
    'Paige Bueckers',
    'Donruss',
    2026,
    'wnba',
    'single',
    'Green Laser',
    '/399',
    'Raw',
    4200,
    null,
    1,
    'Numbered green laser, /399. Rated rookie. Corners and edges look strong. One copy in the case.',
    'wnba-holo',
    true,
    2
  ),
  (
    'wemby-prizm-rc-silver',
    'Victor Wembanyama Prizm Silver RC',
    'Victor Wembanyama',
    'Panini Prizm',
    2023,
    'basketball',
    'single',
    'Silver',
    null,
    'Raw',
    7800,
    9500,
    1,
    'The silver RC everyone still asks for. Raw, well-centered, no obvious surface hits. Listed as a single buy link.',
    'bball-chrome',
    true,
    1
  ),
  (
    'aja-wilson-optic-holo',
    'A''ja Wilson Donruss Optic Holo',
    'A''ja Wilson',
    'Donruss Optic',
    2025,
    'wnba',
    'single',
    'Holo',
    null,
    'Raw',
    1800,
    null,
    2,
    'Optic holo of the reigning force in the paint. Two copies on hand.',
    'wnba-holo',
    false,
    2
  ),
  (
    'angel-reese-select',
    'Angel Reese Select Concourse',
    'Angel Reese',
    'Select',
    2025,
    'wnba',
    'single',
    'Concourse',
    null,
    'Raw',
    1200,
    null,
    1,
    'Select concourse, clean color. A cheap hit that still photographs well in a show chat.',
    'wnba-holo',
    false,
    2
  ),
  (
    'jalen-williams-prizm',
    'Jalen Williams Prizm Base',
    'Jalen Williams',
    'Panini Prizm',
    2025,
    'basketball',
    'single',
    'Base',
    null,
    'Raw',
    1600,
    null,
    1,
    'Thunder wing, Prizm base. Sharp enough to grade if you want — listed as a raw single.',
    'bball-chrome',
    false,
    1
  ),
  (
    'napheesa-collier-auto-99',
    'Napheesa Collier Donruss Auto /99',
    'Napheesa Collier',
    'Donruss',
    2026,
    'wnba',
    'auto',
    'On-card',
    '/99',
    'Raw',
    4800,
    null,
    1,
    'On-card auto, numbered /99. Ink is dark and sits in the sweet spot. One in the vault.',
    'auto',
    true,
    2
  ),
  (
    'kahleah-copper-patch',
    'Kahleah Copper Jersey Series Patch',
    'Kahleah Copper',
    'Jersey Series',
    2025,
    'wnba',
    'relic',
    'Patch',
    null,
    'Raw',
    1400,
    null,
    1,
    'Color-matched patch relic. Not a 1/1, but a clean game-used look for a Mercury PC.',
    'patch',
    false,
    2
  ),
  (
    'bo-nix-prizm-rc',
    'Bo Nix Prizm Silver RC',
    'Bo Nix',
    'Panini Prizm',
    2024,
    'football',
    'single',
    'Silver',
    null,
    'Raw',
    3200,
    4000,
    1,
    'Broncos silver RC. Surface is better than most Prizm football. One copy.',
    'nfl',
    true,
    null
  ),
  (
    'julio-rodriguez-chrome',
    'Julio Rodriguez Topps Chrome',
    'Julio Rodriguez',
    'Topps Chrome',
    2025,
    'baseball',
    'single',
    'Refractor',
    null,
    'Raw',
    2200,
    null,
    1,
    'Chrome refractor of the Mariners star. PNW-relevant and priced to move.',
    'mlb',
    false,
    null
  ),
  (
    'antihero-chrome-001',
    'Anti-Hero Chrome #001',
    'Anti-Hero',
    'Cascadia Chrome',
    2026,
    'nonsport',
    'single',
    'Chrome',
    null,
    'Raw',
    1800,
    null,
    2,
    'Original Cascadia Chrome non-sport. Red and charcoal antihero on a silver frame. Two copies for the comic night.',
    'comic',
    false,
    3
  ),
  (
    'rain-city-sticker-12',
    'Rain City Stickers #12 Bog Lurker',
    'Bog Lurker',
    'Rain City Stickers',
    2026,
    'nonsport',
    'single',
    'Base',
    null,
    'Raw',
    800,
    null,
    4,
    'Original sticker-card from the Rain City set. Ugly on purpose. Four copies.',
    'gpk',
    false,
    3
  ),
  (
    '2026-prizm-hobby-spot',
    '2026 Prizm Basketball Hobby — Random Team Spot',
    null,
    'Panini Prizm Hobby',
    2026,
    'basketball',
    'break-spot',
    null,
    null,
    null,
    3500,
    null,
    11,
    'One random NBA team in a 2026 Prizm hobby break. Spots are first-come via this link. What you pull is yours; the vault ships after the break.',
    'box',
    true,
    1
  ),
  (
    '2026-wnba-fotl-spot',
    '2026 WNBA Prizm FOTL — Spot',
    null,
    'Panini Prizm FOTL',
    2026,
    'wnba',
    'break-spot',
    null,
    null,
    null,
    2400,
    null,
    7,
    'A spot in the First Off The Line WNBA Prizm break. Seven left. Share the drop if you want the rest of the room in.',
    'box',
    false,
    2
  ),
  (
    'chet-holmgren-optic',
    'Chet Holmgren Donruss Optic',
    'Chet Holmgren',
    'Donruss Optic',
    2024,
    'basketball',
    'single',
    'Base',
    null,
    'Raw',
    1100,
    null,
    0,
    'Sold. Left listed so the old buy link still resolves.',
    'bball-chrome',
    false,
    1
  ),
  (
    'sga-donruss-base',
    'Shai Gilgeous-Alexander Donruss Base',
    'Shai Gilgeous-Alexander',
    'Donruss',
    2025,
    'basketball',
    'single',
    'Base',
    null,
    'Raw',
    600,
    null,
    3,
    'Base Donruss, three copies. Cheap PC filler or a show giveaway.',
    'bball-chrome',
    false,
    null
  );
