/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as DropSlugRouteImport } from './routes/drop.$slug'
import { Route as OrderCodeRouteImport } from './routes/order.$code'
import { Route as OrderStripeRouteImport } from './routes/order.stripe'
import { Route as VCodeRouteImport } from './routes/v.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DropSlugRoute = DropSlugRouteImport.update({
  id: '/drop/$slug',
  path: '/drop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCodeRoute = OrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStripeRoute = OrderStripeRouteImport.update({
  id: '/order/stripe',
  path: '/order/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const VCodeRoute = VCodeRouteImport.update({
  id: '/v/$code',
  path: '/v/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRoute
  '/drops': typeof DropsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/scores': typeof ScoresRoute
  '/shop': typeof ShopRoute
  '/c/$slug': typeof CSlugRoute
  '/drop/$slug': typeof DropSlugRoute
  '/order/$code': typeof OrderCodeRoute
  '/order/stripe': typeof OrderStripeRoute
  '/v/$code': typeof VCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRoute
  '/drops': typeof DropsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/scores': typeof ScoresRoute
  '/shop': typeof ShopRoute
  '/c/$slug': typeof CSlugRoute
  '/drop/$slug': typeof DropSlugRoute
  '/order/$code': typeof OrderCodeRoute
  '/order/stripe': typeof OrderStripeRoute
  '/v/$code': typeof VCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRoute
  '/drops': typeof DropsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/scores': typeof ScoresRoute
  '/shop': typeof ShopRoute
  '/c/$slug': typeof CSlugRoute
  '/drop/$slug': typeof DropSlugRoute
  '/order/$code': typeof OrderCodeRoute
  '/order/stripe': typeof OrderStripeRoute
  '/v/$code': typeof VCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/desk'
    | '/drops'
    | '/live'
    | '/login'
    | '/scores'
    | '/shop'
    | '/c/$slug'
    | '/drop/$slug'
    | '/order/$code'
    | '/order/stripe'
    | '/v/$code'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/desk'
    | '/drops'
    | '/live'
    | '/login'
    | '/scores'
    | '/shop'
    | '/c/$slug'
    | '/drop/$slug'
    | '/order/$code'
    | '/order/stripe'
    | '/v/$code'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/desk'
    | '/drops'
    | '/live'
    | '/login'
    | '/scores'
    | '/shop'
    | '/c/$slug'
    | '/drop/$slug'
    | '/order/$code'
    | '/order/stripe'
    | '/v/$code'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DeskRoute: typeof DeskRoute
  DropsRoute: typeof DropsRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  ScoresRoute: typeof ScoresRoute
  ShopRoute: typeof ShopRoute
  CSlugRoute: typeof CSlugRoute
  DropSlugRoute: typeof DropSlugRoute
  OrderCodeRoute: typeof OrderCodeRoute
  OrderStripeRoute: typeof OrderStripeRoute
  VCodeRoute: typeof VCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop/$slug': {
      id: '/drop/$slug'
      path: '/drop/$slug'
      fullPath: '/drop/$slug'
      preLoaderRoute: typeof DropSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$code': {
      id: '/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof OrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/stripe': {
      id: '/order/stripe'
      path: '/order/stripe'
      fullPath: '/order/stripe'
      preLoaderRoute: typeof OrderStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$code': {
      id: '/v/$code'
      path: '/v/$code'
      fullPath: '/v/$code'
      preLoaderRoute: typeof VCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DeskRoute: DeskRoute,
  DropsRoute: DropsRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  ScoresRoute: ScoresRoute,
  ShopRoute: ShopRoute,
  CSlugRoute: CSlugRoute,
  DropSlugRoute: DropSlugRoute,
  OrderCodeRoute: OrderCodeRoute,
  OrderStripeRoute: OrderStripeRoute,
  VCodeRoute: VCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
